### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by pedrorgirardi** [PEZ/clojure4vscode#13]
What you think about the idea of working a little bit on Calva's *branding*? What about presenting Calva more like a product?

What you think about this: **Calva: Clojure & ClojureScript IDE for VSCode**

**Comment by PEZ** [comment]
I totally like the idea to work some on he branding. But wasn't it you who said many people have a psychological aversion towards IDEs? 😃

I definitely think we should include Clojurescript in there.

For branding the icon and the name are most important if we look at it from the extensions pane of VS Code. It also shows part of the tagline. VS Code is given there. People probably also think the rating is important (might not be strictly branding, but definitely impacting the brand).

On the Marketplace there is again the icon, name and tagline. The previews produced when sharing a link to the Marketplace page on many sites present these nicely. But VSCode is not mentioned unless the extension references it.

When I have searched the web for discussions about Clojure(script) support for VS Code it seems that the integrated/interactive REPL is important. There also seems to be that many people are concerned about the experience for beginners. (While I certainly hope to be able to help with lowering the thresholds for Clojure(script) beginners, I hesitate to make that part of the branding, since I do hope that Calva should be able to support real world projects by experienced Clojurians). 

I'll put the icon aside for now and dig where you started digging. Here's another suggestion with my above thoughts in mind:

**Calva: Clojure & Clojurescript interactive programming**
_Integrated REPL, linting, inline eval and more for VSCode. Powered by Cider & nRepl._

Without spelling out **for beginners**, we could utilise what you said in another issue, that Calva just works like so, maybe:

**Calva: Clojure & Clojurescript interactive programming made easy**

What are your thoughts on those suggestions and this rambling of mine?

**Comment by pedrorgirardi** [comment]
Yep, I like it! It’s funny you said the thing about ‘IDE’, because I thought that when I was writing it. But what I meant when said that people are afraid of IDEs I was thinking about things like Eclipse, IntelliJ, Visual Studio. But you are totally right and I agree with you.

I’m moving house tomorrow so I need to finish packing (lol) but I will come back to this later.

Thanks for taking the time to elaborate on this!

**Comment by pedrorgirardi** [comment]
@PEZ  you reckon we could close this one?

**Comment by PEZ** [comment]
Yeah, we have implemented most of the ideas.
