### ISSUE TITLE
Can't connect to new REPL if VSCode was started first

### ISSUE THREAD

**Issue by tjbrandt** [PEZ/clojure4vscode#2]
I really enjoy using the integrated terminal in VSCode, so I tend to start my repl using `lein repl` from there.

I've noticed that clojure4vscode allows you to connect to a _new_ REPL port if it was able to connect to some REPL at startup. But if you start VSCode first, there's no way to connect to a newly started REPL.

This is what I have to do to get it to work, which isn't ideal:
- Start a REPL on your clojure project from a terminal somewhere
- Open your clojure project in VSCode
- Notice that clojure4vscode connects to the REPL successfully
- Start a REPL from VSCode's integrated terminal
- Click on the nrepl address in the task bar and it pops up a text box that allows you to connect to the REPL in the integrated terminal

This is what I would _like_ to work:
- Open your clojure project in VSCode
- Start a REPL from VSCode's integrated terminal
- Click on the `nrepl - trying to connect` label in the task bar, which pops up the text box that allows you to put in your newly-started REPL address

If this is supposed to work already and I'm doing something wrong, please let me know!

Really liking what you've done with this plugin so far. Nice work!

**Comment by PEZ** [comment]
Hello! Very nice to hear from you. I have been dying to get some feedback on how the extension works out there.

I am not sure I understand the process described completely, so please bear with me if I seem to answer it with nonsense. =) This is the process I have intended to support:

1. Start the REPL from a terminal somewhere.
2. Open the project in VS Code
3. Notice that clojure4vscode connects to the REPL.
4. Start bending reality with the power of Clojure.

The reason I've not put effort into starting the real from VS Code is that the project I work most on takes a while to start, and if I need to restart VS Code I don't like the penalty to wait for it to start the REPL again.

I _think_ your desired process is almost supported if you use the **Reconnect** command. And I can certainly make it so that if no `.nrepl-port` file is found, the connection label in the status bar is clickable.

This all said. Just a few hours before you filed this issue I updated the plugin so that it automatically starts a REPL in the terminal connected to the REPL started from a terminal somewhere. And I am thinking that maybe you haven't/hadn't seen that update yet? With this version you get some more commands that helps working with the terminal REPL together with the code being edited, such as switching to the edited namespace, and evaluating code being edited in the terminal REPL.

Please let me know if you have tried version 1.2 yet and what you think about it, if so.

Hoping you will keep finding this extension useful. And will put in work to make it so. 🤠

**Comment by tjbrandt** [comment]
Hi Peter! Thanks for the reply. You're right that I hadn't seen the update before I filed the issue.

After updating and coming back to the plugin, the **Reconnect** command does indeed do what I'm looking for, so I'm a happy camper! I'll close this issue out.

I've been considering abandoning VSCode for my Clojure work because it seems to miss some important features that Atom supports, but I don't like Atom nearly as much as an editor. However, the inline evaluation of forms and the "evaluate and send to REPL" functions of your extension help tremendously with my VSCode satisfaction!

If I were to choose the one big thing that bothers me about Clojure in VSCode (besides the fact that the parinfer extension is a little buggy and [isn't actively supported](https://github.com/shaunlebron/vscode-parinfer/issues/22)), it would be auto-indent support that follows the [style-guide](https://github.com/bbatsov/clojure-style-guide). Maybe something you could potentially put on your to-do list if you're taking requests 😄

**Comment by PEZ** [comment]
Glad your workflow is working again! Still curious about you think of the integrated Terminal REPL support, please feel invited to file more issues or just comment on that in this thread.

I haven't noticed the auto-indent thing. Can you tell a way or two it fails? (I mostly use Paredit to get things indented, and  haven't studied the style guide very closely.)

Didn't know the parinfer extension was abandonware. That is not good and explains some of the pain it deals out, but it still is delivering much more bliss so still using it. Maybe you should make ourself available as the maintainer? 🤠

**Comment by PEZ** [comment]
One more thing. I think your way of starting the REPL would benefit from configuring the extension to not autoconnect to the REPL:

```"clojure4vscode.autoConnect": false```

(I also think starting the REPL from the internal terminal will get a bit confusing with the internal terminal REPL that the extension starts upon connecting, but anyway. 😀)

**Comment by PEZ** [comment]
Thanks. I'll have a look at how these things are determined in VS Code. The responsibilities among the different plugins and core VS Code are unclear to me. But it makes some sense that this plugin should try take care of autoindenting.

**Comment by tjbrandt** [comment]
And just to follow-up about the parinfer extension... suddenly it's working a lot better, even though there hasn't been any updates. I wonder if something about VSCode got updated or maybe turning paredit back on somehow makes it interact and work better, though I don't see how. But it's suddenly feeling very usable to me, which is awesome! Honestly, if all this keeps working in conjunction with your plugin, the only Clojure integration that I would really feel like VSCode is missing is the auto-indentation issue. That would be _amazing_. If you decide to tackle it sometime, I'd be happy to help you test and give suggestions for different indentation cases. (Least I could do, of course, given that you're doing the heavy lifting.)

**Comment by PEZ** [comment]
Hello. Started a new issue, #3, for this auto-indentation business. Please feel invited to add more examples.

See also #4.
